language: node_js
#  latest stable Node.js release
node_js: node
branches:
  only:
  - master
script: npm run generate
deploy:
  # Keep dist folder for deploy
  skip_cleanup: true
  provider: firebase
  token:
    secure: L/UAkAWLM/+GPflHbpFh3cPa7475WgMVd9BFKeWo89dquWyMLbFaLFaxHxYXLcWcIgUMCVe5y1g1qbPpRChDb0kHUU5ATFMUNQBiWDsjOZq8FjrtW1rNgIWpo/so1iykQGhamALoOUiqsZkKuemDknRPEjI7IZqCaflHyPhkuDmSPqA+bqFOfd+eP4GOTA9gMLbTrV7oVs6kWYv0KwlPdW/B2blzLddfYBGcU+xphffDxkMgerqP4t+IHp44T4qKsvOBBNksqEiCc5DYSSh4OWiNSeC/SzRiVFGEvz1cA0clMbtT1pNgW5E3j2lGMuzFm3Wc7sBjNQuX9CYVsy8RcEzqJ+4g6cdVhVFYxRZD11/b8SlgieBs7YrGU60ByoyAB1XqLal+cZBARtqorEzs6JLVTHEcVd4zYa9ge5GvbD736Pg/2OuL272meZo2RW4clPatoLXb1DIHljij0SVI9ry7i8oCl+s0sgPm+MSvRXFvSL9pWGFJ4LjKcTGQzQEDk2Vkb9OZgJ6acT5sjfb7Rroj0XeyM7Y9lgTOD6b9JytpLe3jCEA0EXHy4HB6rRoT+JvA8DUmWuI17/ya5K9a5PMn699GeaUc2QK/7R+wNhovJof9E+fyXtBsufMm+62J6wCn42+o7G4jbPeX0DIf9mQ4XDixpSmrmgj/UjgDbY8=
cache: npm
env:
  global:
  - secure: L/UAkAWLM/+GPflHbpFh3cPa7475WgMVd9BFKeWo89dquWyMLbFaLFaxHxYXLcWcIgUMCVe5y1g1qbPpRChDb0kHUU5ATFMUNQBiWDsjOZq8FjrtW1rNgIWpo/so1iykQGhamALoOUiqsZkKuemDknRPEjI7IZqCaflHyPhkuDmSPqA+bqFOfd+eP4GOTA9gMLbTrV7oVs6kWYv0KwlPdW/B2blzLddfYBGcU+xphffDxkMgerqP4t+IHp44T4qKsvOBBNksqEiCc5DYSSh4OWiNSeC/SzRiVFGEvz1cA0clMbtT1pNgW5E3j2lGMuzFm3Wc7sBjNQuX9CYVsy8RcEzqJ+4g6cdVhVFYxRZD11/b8SlgieBs7YrGU60ByoyAB1XqLal+cZBARtqorEzs6JLVTHEcVd4zYa9ge5GvbD736Pg/2OuL272meZo2RW4clPatoLXb1DIHljij0SVI9ry7i8oCl+s0sgPm+MSvRXFvSL9pWGFJ4LjKcTGQzQEDk2Vkb9OZgJ6acT5sjfb7Rroj0XeyM7Y9lgTOD6b9JytpLe3jCEA0EXHy4HB6rRoT+JvA8DUmWuI17/ya5K9a5PMn699GeaUc2QK/7R+wNhovJof9E+fyXtBsufMm+62J6wCn42+o7G4jbPeX0DIf9mQ4XDixpSmrmgj/UjgDbY8=
  - CODECOV_TOKEN="646222d4-c5b3-4703-98da-62670ea75e31"
  - secure: Su+HMCBStmQkHxNK1LL9W9pm4is4nsrdD5C1mvjGgJ87WNS0DTDk+l8DIiZ9/uMg7Rp/eEsj67oqblCD+3VmLZVwdpolYGmOKVWC71chjPzODa/X15X4bXXdKfvSX0F7CzDRmVJ/vO7YWh/Py8CKvj75OsSwr1NgLBeBaqSF9P0B4/VLopVLOUCh2TAUl4rdf+u1EXtsWqsdExMJFaDq+ke+0hNUQ2O8f3bPiXx6f7xwA7lSDGbB5TlKo7brUeBO2eiapP0YBypKJ6wrXc2VZbvdrvYq3Gw0mooAZedonfYspDVlXNQct4C1542Qs7T27ByURhqm2y+3P/QKxx66laF0ifaKmFv2OO6NTDvN90WZU394ctSm8LvGzfJImhONcr42Hpr1bVvmHWxYvRzc/UyTXI2CreFP0EhkrbHyhIS/6cgi9PaDxFl9Ts3RZMuzlWYIYZXhSjmhogEuFGGemqHpThfJGG5EFj7CZR0f5NED51aIPtPSOMjC0WTMbCqAETS2Vsr1FUZDGZJVUXjK0TCqA+8UXBTQeVyUFqfuGdhOSWszfNDOYQi1mNtDo4g05dNDnPPC8ItdaA3FeMw9fxBqeH5ffTUqZ8F4Z+76ACN/F70Hpy0d0NmnmMnssiwfn5RJCz939WwgdR0wpcCFVY8eLGR6FnjI05XX625bupc=
  - secure: M+A8ISnwOzaw+KeTTyPSlzBFS2eywDSGBUh0LoudNeVWJEl0Pql4PrQCYq2KlYAXF+fgLhmt44djA9zZP8X+fRU5V81x+63FSDm0pWDiiWzaacEb2nVLn1eaaNK6eqmTvWI27nS37O9vPWSMhcv+nxrIkvrxKNvhAhuD1SPUCv9ZIJj7fT0xia50pk8+/itMe/MMqBgm3W4FwSvKvSG+VBMLB+NX9A6TTthFuIPAdk3CE9SeWTcRDLnybwIiDtMuojwCUiTac9Sg9FmuyPHZupf2o6x6j9LxzxjJZ3lrD3nFhTM8g5nup77aMaykmOGwnZLqszW8A7Y105WdXK8oOsqi9Jt6zErUpkjc+kBf5s0nEZW0RD4uMJP2PP1TvWz8lcwZHwGWcx1C3d6Twvf6JvIAi4EyvNzL4yaoM4gCa7jLgRTgASgGRpvz3JtjxosS6irZUQ4TErfYtD57ZEUWjAJh1GgIC2y4CLCgn5nWlr8gXUtH5Hro/kk71+eHnCc6gjU3OiHA217J7zCXt1GRqKa+hr/NtKbDdI1oy4WQ/Gq9dS6cK0q7KzkxMXexgpLo9BUgt6MDewdDdYc3YVQCm6DP/i3GfHF8CWNNTvgwW2tklkJta7s5t+bWWL2I5QegEJVVTjSWH1vmVO0JPvZcAC1amj/oQse1rRRedT7C/Hg=
notifications:
  email:
    recipients:
    - damien.robinson@pocketpasta.com
    on_success: always
    on_failure: always
